version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - JWT_SECRET="cookies"
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
      - PORT="4000"
      - NODE_ENV="dev"
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      - VITE_APP_API_URL="http://localhost:4000"
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: